name: my_expenses
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.8
  intl: ^0.18.0
  flutter_localization: ^0.1.9
  lottie: ^1.4.3
  sqflite: ^2.2.2
  path: ^1.8.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  mocktail: ^0.3.0
  

flutter: 
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/sucess.json